spring.application.name=SpringDemo-producerestapi
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username= root
spring.datasource.password= #Aruna3786

server.servlet.context-path=/productapi
